Refactor
husarion/rosbot-xl-sensors pull request #1
Opened 2023-09-19 08:37 UTC by rafal-gorecki

2023-09-19 09:36 UTC, delihus commented on README.md
> +:::info
```suggestion
```

2023-09-19 09:38 UTC, delihus requested changes
The `:::info` doesn't render on Github. Maybe Note will be good. The rest is great!

![image](https://github.com/husarion/rosbot-xl-sensors/assets/109142865/f140fb91-897f-4ecd-8504-0824dc0f0a48)

For e.g.
![image](https://github.com/husarion/rosbot-xl-sensors/assets/109142865/980de28a-ca8c-49f1-b930-1b361fcfbe4e)

2023-09-19 09:38 UTC, delihus commented on README.md
> +:::info
```suggestion
> [!NOTE]
```

2023-09-19 09:38 UTC, delihus commented on README.md
> +You should use **Chrome/Chromium** browser.
```suggestion
> You should use **Chrome/Chromium** browser.
```

2023-09-19 09:38 UTC, delihus commented on README.md
> +:::
```suggestion
```

2023-09-19 10:17 UTC, delihus commented
Please add info how to flash the correct version of firmware from `husarion/rosbot-xl:humble-0.8.2-20230913`.

2023-09-19 11:04 UTC, delihus approved these changes
Thanks!

2023-09-20 10:16 UTC, JanBrzyk approved these changes, later dismissed

2023-09-20 11:59 UTC, JanBrzyk approved these changes

2023-09-20 12:00 UTC, JanBrzyk approved these changes

2023-09-20 12:00 UTC, merged